### ISSUE TITLE
Not working on text fields only on checkboxes

### ISSUE THREAD

**Issue by danijelBalaban** [rtpHarry/jet-engine-repeater-values#3]
Hi Matt,

I have this issue where if i set the dynamic visibility to hide a repeater field based on the repeater key (text) nothing happens, but if i try another workaround by adding a checkbox to the repeater field and have the condition say show element if value is checked (Jet Engine specific) then your plugin works just fine.

What could be the issue here?

**Comment by EquilibriumTechx** [comment]
Yes, don't seem to be working on a text field inside the repeater.

**Comment by rtpHarry** [comment]
I'm not sure about the answer for this. Have you got your question the right way around? 

Based on what I just worked on with #2 I didn't think there was any support with this plugin for checkboxes, until I just released v1.2.beta.2.

When I test it with an "equals" or "not equals" on a JetEngine Meta Field of type Text, it is working as expected.

For example, I'm saying only show the heading if the artist-bio repeater field is not equal to De La Soul

<img width="309" alt="image" src="https://user-images.githubusercontent.com/1038062/159054221-eb4afed8-0a6c-41ff-9c5d-eecddb2c0217.png">

And that's working as expected for me:

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/1038062/159054285-cfa53016-967b-494d-a633-7e2673055bb7.png">

**Comment by rtpHarry** [comment]
I'm going to close this issue now as I didn't understand it, but if you want to add more info and reopen it then please do.

**Comment by danbalaban** [comment]
I'll take my time to add screenshots so you get a better understanding what's up. I know it's difficult otherwise. Thanks for your time to respond.

**Comment by danbalaban** [comment]
@rtpHarry sorry i haven't gotten the notification on your first response so i'll try to explain this in detail as much as i can.

I have a CPT called Projects and a single projects template which uses repeater fields to show project features which vary from project to project. In total there are ten different project features (details & finishes, awards & recognitions, parking deck details, etc) and each project uses usually two out of those ten features, so the ones which are not used i want to dynamically hide if the repeater field is not used.

![4-4-2022_39S24sx10F](https://user-images.githubusercontent.com/21226901/162229568-22c85c7a-e3c7-431e-953b-837fbae267dd.jpeg)

I would like to skip adding the checkbox field to each repeater field because it's just unecessary (but that does work in hiding the element with your plugin) and find a way how to set the visibillity not to show empty repeater elements.

![4-4-2022_s2CyL4dzdG](https://user-images.githubusercontent.com/21226901/162229436-309a2938-8682-450f-ab4b-68700f7c4dd6.jpeg)

Whatever i try with the conditions it just doesn't work, except if i add an additional checkbox in the repeater field and set the conditions if value is/not checked (ideally i would like to avoid that).

Any idea what can be done?
